### PR TITLE
Check if Scala files are formatted on CI

### LINKED ISSUE #15737: Custom-views: Fail CI on scalafmt change
CI build should check scalafmt and fail if it is not formatted.

### PR DESCRIPTION
**Pull request by cbley-da**
Fixes digital-asset/daml#15737

### CODE REVIEW

**Review by chunlokling-da — APPROVED** [review]

**Comment by chunlokling-da** [comment]
Shall we commit some file which will not pass the check and see if the CI failed here?

**Comment by cbley-da** [comment]
> Shall we commit some file will not pass the check and see if the CI failed here?

Yeah, thought about this too. Let's try :+1:

**Review by ray-roestenburg-da — APPROVED** [review]

**Comment by cbley-da** [comment]
@ray-roestenburg-da it failed on CI expectedly (for the non-formatted `build.sbt`), but since the "lint" test is not required, one could still squash and merge. Can you enable the "required" checkbox in the settings please?

**Comment by ray-roestenburg-da** [comment]
@cbley-da I do not have the power. @garyverhaegen-da @nycnewman can you help with enabling the "required" checkbox in the settings please?

**Comment by garyverhaegen-da** [comment]
> @cbley-da I do not have the power. @garyverhaegen-da @nycnewman can you help with enabling the "required" checkbox in the settings please?

Done.

It's a bit weird: we usually get a signal from CircleCI for the workflow. It looks like on this repo we only get individual jobs? I'm not sure why that happens, but the consequence is any time you add a new job you'll have to update the branch protection rules (or ask an admin to, I suppose).

**Pull request merged**
